In [11]:
#indexing of array
#accesing the original array
import numpy as  np
x=np.array([1,2,3,4,5,6,7])
print(x[1:3])
print(x.shape)

[2 3]
(7,)


In [3]:
#slicing of index
# slicing is extracting from one element and assigning to another element
x=np.array([1,2,3,4,5,6,7])
y=(x[1:3])
print(y)

[2 3]


In [19]:
#iterating
arr4=np.array([[1,2,3,4],[2,5,6,7]])
for x in arr4:
    print(x)


[1 2 3 4]
[2 5 6 7]


In [15]:
#reshaping
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,13])
print(arr.reshape(4,3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]


In [20]:
#tuple is an ordered list
#you can only reshape1-D to 2-D or 3-D and also 4-D to 2-D or 3-D to 1-D but not posssible from2-D to 3-D


In [21]:
#joining
arrx=np.array([1,2,3,4])
arrx1=np.array([2,5,6,7])
arrx2=np.concatenate((arrx,arrx1))
print(arrx2)

[1 2 3 4 2 5 6 7]


In [26]:
#splitting
arrx=np.array([1,2,3,4,5,6,7,8])
a=np.array_split(arrx,3)
print(a)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
